backend:
  name: github
  repo: skrytskaya/gastroverdictblog 

media_folder: static/uploads
public_folder: /uploads
media_library:
  name: uploadcare
  config:
    publicKey: d3e17c625e7b2f388482

collections:
  - name: "blog"
    label: "Blog"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false, media_library: {config: {multiple: true, previewStep: false}}}
      # - {label: "Alt", name: "alt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown" }
