backend:
  name: github
  repo: skrytskaya/gastroverdictblog

media_folder: static/assets

collections:
  - name: content
    label: Content
    folder: content
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: date, label: Date, widget: date }
      - { name: image, label: Image }
      - { name: tags, label: Tags }
      - { name: body, label: Body, widget: markdown }