 name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/uploads
public_folder: /uploads
collections:
  - name: "blog"
    label: "Blog"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false, media_library: {config: {multiple: true, previewStep: false}}}
      # - {label: "Alt", name: "alt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown" }
